// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

public class FindDifference {
  public char findTheDifference(String s, String t) {
    int[] count = new int[26];
    for (int i=0; i<s.length(); i++) {
      count[s.charAt(i) - 'a'] += 1;
      count[t.charAt(i) - 'a'] -= 1;
    }
    count[t.charAt(s.length()) - 'a'] -= 1;
    for (int i=0; i<26; i++) {
      if (count[i] != 0)
        return (char)('a' + i);
    }
    return 0; // We should not reach here
  }

  public static void Run() {
    FindDifference f = new FindDifference();
    System.out.println(f.findTheDifference("abcd", "abcde"));
    System.out.println(f.findTheDifference("", "y"));
  }
}
